# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e43e7c432b0b3cdfe4eea077556d0c4f46bde9245b19cdb854b96702c63440a3d1bd4328ea21c283f1c38d0a32bbf0db8eafb474deecdb5eb54a35351f7a98

test:
  secret_key_base: 1a7d2f4951780b55f4a9bfadcd7860363f85d9f7336e710a6e1fda781b683f32158c64517d93700aaa24a8f581811f62fab06314b91b7ca8bbe651c1765f8b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
